### ISSUE TITLE
Kubernetes - subdomains should use controller load balancer with service without load balancer

### ISSUE THREAD

**Issue by martinlevesque** [openode-io/openode-api#149]
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: mynamespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
  namespace: mynamespace
spec:
  selector:
    matchLabels:
      app: kuard
  replicas: 1
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - image: openode/openode_prod:nodetest  #gcr.io/kuar-demo/kuard-amd64:1
        imagePullPolicy: Always
        name: kuard
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: kuard-service
  namespace: mynamespace
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: kuard
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuard
  namespace: mynamespace
  annotations:
    kubernetes.io/ingress.class: "nginx"

spec:
  rules:
  - host: 6ojq5t5np0.lb.c1.bhs5.k8s.ovh.net # nginx controller external ip
    http:
      paths:
      - path: /
        backend:
          serviceName: kuard-service
          servicePort: 80
  - host: mytest.nodetests.openode.io
    http:
      paths:
      - path: /
        backend:
          serviceName: kuard-service
          servicePort: 80
---
```
