### ISSUE TITLE
Detect lacks of memory, OOMKilled

### ISSUE THREAD

**Issue by martinlevesque** [openode-io/openode-api#236]
```
containerStatuses:
  - containerID: docker://93408c458fe0df94c01757cc938118053a95c7eb6576f38afd6037bae0096553
    image: registry.digitalocean.com/production-openode/XXX:XXX--16720--4763
    imageID: docker-pullable://registry.digitalocean.com/production-openode/XXX@sha256:42481b1361984e739a783653aff2d47c4367e7448bae55864d950093cc6b9259
    lastState:
      terminated:
        containerID: docker://93408c458fe0df94c01757cc938118053a95c7eb6576f38afd6037bae0096553
        exitCode: 0
        finishedAt: "2020-03-31T14:59:23Z"
        reason: OOMKilled
        startedAt: "2020-03-31T14:59:23Z"
```
