### ISSUE TITLE
client IP is not passed to request headers

### ISSUE THREAD

**Issue by martinlevesque** [openode-io/openode-api#431]
u=14424

should use NGINX configmap 

```
apiVersion: v1
data:
  use-proxy-protocol: "true"
kind: ConfigMap
metadata:
  name: nginx-ingress-controller
```

and needs to annotate load balancer

`kubectl annotate service nginx-ingress-controller service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol=true`

Need to deep test with 

```
From: https://helm.sh/docs/intro/quickstart/#initialize-a-helm-chart-repository
 
helm repo add stable https://kubernetes-charts.storage.googleapis.com/
helm install nginx-ingress stable/nginx-ingress
```

Need to test:
- All NGINX/kube configs (ex. web sockets, ssl, etc.)
- switching from quickstart to stable/nginx-ingress with existing deployments
