### ISSUE TITLE
Force redirect HTTP-HTTPS

### ISSUE THREAD

**Issue by martinlevesque** [openode-io/openode-api#584]
```
http:

  routers:
    router-1:
      
      rule: "Host(`gcloudruntest.cronrobot.io`)"
      service: "service-1"
      tls: {}

    router-1-http:
      rule: "Host(`gcloudruntest.cronrobot.io`)"
      entryPoints:
        - web
      service: "service-1"
      #middlewares:
      #  - https

  middlewares:
    https:
        redirectScheme:
          scheme: https
```
